version: '3.7'

networks:
  default:

volumes:
  redis:
  letsencrypt:

services:
  nginx:
    image: ${NGINX_IMAGE}
    deploy:
      mode: global
    # This port format is needed to get real ip address of the client
    ports:
      - target: 8080
        published: 80
        mode: host
      - target: 8443
        published: 443
        mode: host
    volumes:
      - letsencrypt:/etc/letsencrypt

  redis:
    image: 'redis:6-alpine'
    volumes:
      - redis:/data

  # This naming of the docker containers completely defeats the
  # purpose of Docker swarm and docker load balancing
  # so we are instead handling the load balancing with
  # our own nginx container
  relay0:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0
